/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onycom_ImageMatchingJNI_Main */

#ifndef _Included_com_onycom_ImageMatchingJNI_Main
#define _Included_com_onycom_ImageMatchingJNI_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onycom_ImageMatchingJNI_Main
 * Method:    matchImage
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Z)D
 */
JNIEXPORT jdouble JNICALL Java_com_onycom_ImageMatchingJNI_Main_matchImage
  (JNIEnv *, jclass, jstring, jobject, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
